// Scan License Plate
export const SCAN_PLATE_REQUEST = 'SCAN_PLATE_REQUEST';
export const SCAN_PLATE_SUCCESS = 'SCAN_PLATE_SUCCESS';
export const SCAN_PLATE_FAIL = 'SCAN_PLATE_FAIL';
export const SCAN_PLATE_RESET = 'SCAN_PLATE_RESET';

// Get All Scans
export const GET_SCANS_REQUEST = 'GET_SCANS_REQUEST';
export const GET_SCANS_SUCCESS = 'GET_SCANS_SUCCESS';
export const GET_SCANS_FAIL = 'GET_SCANS_FAIL';
export const GET_SCANS_RESET = 'GET_SCANS_RESET';

// Get Single Scan
export const GET_SCAN_REQUEST = 'GET_SCAN_REQUEST';
export const GET_SCAN_SUCCESS = 'GET_SCAN_SUCCESS';
export const GET_SCAN_FAIL = 'GET_SCAN_FAIL';
export const GET_SCAN_RESET = 'GET_SCAN_RESET';

// Link Scan to Report
export const LINK_SCAN_REQUEST = 'LINK_SCAN_REQUEST';
export const LINK_SCAN_SUCCESS = 'LINK_SCAN_SUCCESS';
export const LINK_SCAN_FAIL = 'LINK_SCAN_FAIL';
export const LINK_SCAN_RESET = 'LINK_SCAN_RESET';

// Delete Scan
export const DELETE_SCAN_REQUEST = 'DELETE_SCAN_REQUEST';
export const DELETE_SCAN_SUCCESS = 'DELETE_SCAN_SUCCESS';
export const DELETE_SCAN_FAIL = 'DELETE_SCAN_FAIL';
export const DELETE_SCAN_RESET = 'DELETE_SCAN_RESET';

// UI States
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const RESET_SUCCESS = 'RESET_SUCCESS';