export const PUBLISH_BROADCAST_REQUEST = 'PUBLISH_BROADCAST_REQUEST';
export const PUBLISH_BROADCAST_SUCCESS = 'PUBLISH_BROADCAST_SUCCESS';
export const PUBLISH_BROADCAST_FAILURE = 'PUBLISH_BROADCAST_FAILURE';

export const UNPUBLISH_BROADCAST_REQUEST = 'UNPUBLISH_BROADCAST_REQUEST';
export const UNPUBLISH_BROADCAST_SUCCESS = 'UNPUBLISH_BROADCAST_SUCCESS';
export const UNPUBLISH_BROADCAST_FAILURE = 'UNPUBLISH_BROADCAST_FAILURE';

export const GET_BROADCAST_HISTORY_REQUEST = 'GET_BROADCAST_HISTORY_REQUEST';
export const GET_BROADCAST_HISTORY_SUCCESS = 'GET_BROADCAST_HISTORY_SUCCESS';
export const GET_BROADCAST_HISTORY_FAILURE = 'GET_BROADCAST_HISTORY_FAILURE';

