// Basic Analytics
export const GET_BASIC_ANALYTICS_REQUEST = 'GET_BASIC_ANALYTICS_REQUEST';
export const GET_BASIC_ANALYTICS_SUCCESS = 'GET_BASIC_ANALYTICS_SUCCESS';
export const GET_BASIC_ANALYTICS_FAIL = 'GET_BASIC_ANALYTICS_FAIL';

// Type Distribution
export const GET_TYPE_DISTRIBUTION_REQUEST = 'GET_TYPE_DISTRIBUTION_REQUEST';
export const GET_TYPE_DISTRIBUTION_SUCCESS = 'GET_TYPE_DISTRIBUTION_SUCCESS';
export const GET_TYPE_DISTRIBUTION_FAIL = 'GET_TYPE_DISTRIBUTION_FAIL';

// Status Distribution
export const GET_STATUS_DISTRIBUTION_REQUEST = 'GET_STATUS_DISTRIBUTION_REQUEST';
export const GET_STATUS_DISTRIBUTION_SUCCESS = 'GET_STATUS_DISTRIBUTION_SUCCESS';
export const GET_STATUS_DISTRIBUTION_FAIL = 'GET_STATUS_DISTRIBUTION_FAIL';

// Monthly Trend
export const GET_MONTHLY_TREND_REQUEST = 'GET_MONTHLY_TREND_REQUEST';
export const GET_MONTHLY_TREND_SUCCESS = 'GET_MONTHLY_TREND_SUCCESS';
export const GET_MONTHLY_TREND_FAIL = 'GET_MONTHLY_TREND_FAIL';

// Location Hotspots
export const GET_LOCATION_HOTSPOTS_REQUEST = 'GET_LOCATION_HOTSPOTS_REQUEST';
export const GET_LOCATION_HOTSPOTS_SUCCESS = 'GET_LOCATION_HOTSPOTS_SUCCESS';
export const GET_LOCATION_HOTSPOTS_FAIL = 'GET_LOCATION_HOTSPOTS_FAIL';