// Action Types
export const GET_EMERGENCY_CONTACTS_REQUEST = 'GET_EMERGENCY_CONTACTS_REQUEST';
export const GET_EMERGENCY_CONTACTS_SUCCESS = 'GET_EMERGENCY_CONTACTS_SUCCESS';
export const GET_EMERGENCY_CONTACTS_FAIL = 'GET_EMERGENCY_CONTACTS_FAIL';

export const GET_EMERGENCY_CONTACT_REQUEST = 'GET_EMERGENCY_CONTACT_REQUEST';
export const GET_EMERGENCY_CONTACT_SUCCESS = 'GET_EMERGENCY_CONTACT_SUCCESS';
export const GET_EMERGENCY_CONTACT_FAIL = 'GET_EMERGENCY_CONTACT_FAIL';

export const CREATE_EMERGENCY_CONTACT_REQUEST = 'CREATE_EMERGENCY_CONTACT_REQUEST';
export const CREATE_EMERGENCY_CONTACT_SUCCESS = 'CREATE_EMERGENCY_CONTACT_SUCCESS';
export const CREATE_EMERGENCY_CONTACT_FAIL = 'CREATE_EMERGENCY_CONTACT_FAIL';

export const UPDATE_EMERGENCY_CONTACT_REQUEST = 'UPDATE_EMERGENCY_CONTACT_REQUEST';
export const UPDATE_EMERGENCY_CONTACT_SUCCESS = 'UPDATE_EMERGENCY_CONTACT_SUCCESS';
export const UPDATE_EMERGENCY_CONTACT_FAIL = 'UPDATE_EMERGENCY_CONTACT_FAIL';

export const DELETE_EMERGENCY_CONTACT_REQUEST = 'DELETE_EMERGENCY_CONTACT_REQUEST';
export const DELETE_EMERGENCY_CONTACT_SUCCESS = 'DELETE_EMERGENCY_CONTACT_SUCCESS';
export const DELETE_EMERGENCY_CONTACT_FAIL = 'DELETE_EMERGENCY_CONTACT_FAIL';

export const GET_NEAREST_EMERGENCY_CONTACTS_REQUEST = 'GET_NEAREST_EMERGENCY_CONTACTS_REQUEST';
export const GET_NEAREST_EMERGENCY_CONTACTS_SUCCESS = 'GET_NEAREST_EMERGENCY_CONTACTS_SUCCESS';
export const GET_NEAREST_EMERGENCY_CONTACTS_FAIL = 'GET_NEAREST_EMERGENCY_CONTACTS_FAIL';
