// Feedback CRUD Operations
export const CREATE_FEEDBACK_REQUEST = 'CREATE_FEEDBACK_REQUEST';
export const CREATE_FEEDBACK_SUCCESS = 'CREATE_FEEDBACK_SUCCESS';
export const CREATE_FEEDBACK_FAIL = 'CREATE_FEEDBACK_FAIL';

export const GET_FEEDBACKS_REQUEST = 'GET_FEEDBACKS_REQUEST';
export const GET_FEEDBACKS_SUCCESS = 'GET_FEEDBACKS_SUCCESS';
export const GET_FEEDBACKS_FAIL = 'GET_FEEDBACKS_FAIL';

export const GET_MY_FEEDBACK_REQUEST = 'GET_MY_FEEDBACK_REQUEST';
export const GET_MY_FEEDBACK_SUCCESS = 'GET_MY_FEEDBACK_SUCCESS';
export const GET_MY_FEEDBACK_FAIL = 'GET_MY_FEEDBACK_FAIL';

export const GET_FEEDBACK_REQUEST = 'GET_FEEDBACK_REQUEST';
export const GET_FEEDBACK_SUCCESS = 'GET_FEEDBACK_SUCCESS';
export const GET_FEEDBACK_FAIL = 'GET_FEEDBACK_FAIL';

export const UPDATE_FEEDBACK_REQUEST = 'UPDATE_FEEDBACK_REQUEST';
export const UPDATE_FEEDBACK_SUCCESS = 'UPDATE_FEEDBACK_SUCCESS';
export const UPDATE_FEEDBACK_FAIL = 'UPDATE_FEEDBACK_FAIL';

export const DELETE_FEEDBACK_REQUEST = 'DELETE_FEEDBACK_REQUEST';
export const DELETE_FEEDBACK_SUCCESS = 'DELETE_FEEDBACK_SUCCESS';
export const DELETE_FEEDBACK_FAIL = 'DELETE_FEEDBACK_FAIL';

// Admin Response
export const RESPOND_FEEDBACK_REQUEST = 'RESPOND_FEEDBACK_REQUEST';
export const RESPOND_FEEDBACK_SUCCESS = 'RESPOND_FEEDBACK_SUCCESS';
export const RESPOND_FEEDBACK_FAIL = 'RESPOND_FEEDBACK_FAIL';

// Statistics
export const GET_FEEDBACK_STATS_REQUEST = 'GET_FEEDBACK_STATS_REQUEST';
export const GET_FEEDBACK_STATS_SUCCESS = 'GET_FEEDBACK_STATS_SUCCESS';
export const GET_FEEDBACK_STATS_FAIL = 'GET_FEEDBACK_STATS_FAIL';

// State Management
export const CLEAR_FEEDBACK_ERROR = 'CLEAR_FEEDBACK_ERROR';
export const RESET_FEEDBACK_STATE = 'RESET_FEEDBACK_STATE';