// Action Types
export const CREATE_FINDER_REPORT_REQUEST = 'CREATE_FINDER_REPORT_REQUEST';
export const CREATE_FINDER_REPORT_SUCCESS = 'CREATE_FINDER_REPORT_SUCCESS';
export const CREATE_FINDER_REPORT_FAIL = 'CREATE_FINDER_REPORT_FAIL';

export const GET_FINDER_REPORTS_REQUEST = 'GET_FINDER_REPORTS_REQUEST';
export const GET_FINDER_REPORTS_SUCCESS = 'GET_FINDER_REPORTS_SUCCESS';
export const GET_FINDER_REPORTS_FAIL = 'GET_FINDER_REPORTS_FAIL';

export const GET_FINDER_REPORTS_BY_REPORT_ID_REQUEST = 'GET_FINDER_REPORTS_BY_REPORT_ID_REQUEST';
export const GET_FINDER_REPORTS_BY_REPORT_ID_SUCCESS = 'GET_FINDER_REPORTS_BY_REPORT_ID_SUCCESS';
export const GET_FINDER_REPORTS_BY_REPORT_ID_FAIL = 'GET_FINDER_REPORTS_BY_REPORT_ID_FAIL';

export const GET_FINDER_REPORT_DETAILS_REQUEST = 'GET_FINDER_REPORT_DETAILS_REQUEST';
export const GET_FINDER_REPORT_DETAILS_SUCCESS = 'GET_FINDER_REPORT_DETAILS_SUCCESS';
export const GET_FINDER_REPORT_DETAILS_FAIL = 'GET_FINDER_REPORT_DETAILS_FAIL';

export const UPDATE_FINDER_REPORT_REQUEST = 'UPDATE_FINDER_REPORT_REQUEST';
export const UPDATE_FINDER_REPORT_SUCCESS = 'UPDATE_FINDER_REPORT_SUCCESS';
export const UPDATE_FINDER_REPORT_FAIL = 'UPDATE_FINDER_REPORT_FAIL';

export const VERIFY_FINDER_REPORT_REQUEST = 'VERIFY_FINDER_REPORT_REQUEST';
export const VERIFY_FINDER_REPORT_SUCCESS = 'VERIFY_FINDER_REPORT_SUCCESS';
export const VERIFY_FINDER_REPORT_FAIL = 'VERIFY_FINDER_REPORT_FAIL';

export const DELETE_FINDER_REPORT_REQUEST = 'DELETE_FINDER_REPORT_REQUEST';
export const DELETE_FINDER_REPORT_SUCCESS = 'DELETE_FINDER_REPORT_SUCCESS';
export const DELETE_FINDER_REPORT_FAIL = 'DELETE_FINDER_REPORT_FAIL';