// Link Messenger Account
export const LINK_MESSENGER_REQUEST = 'LINK_MESSENGER_REQUEST';
export const LINK_MESSENGER_SUCCESS = 'LINK_MESSENGER_SUCCESS';
export const LINK_MESSENGER_FAIL = 'LINK_MESSENGER_FAIL';
export const LINK_MESSENGER_RESET = 'LINK_MESSENGER_RESET';

// Unlink Messenger Account  
export const UNLINK_MESSENGER_REQUEST = 'UNLINK_MESSENGER_REQUEST';
export const UNLINK_MESSENGER_SUCCESS = 'UNLINK_MESSENGER_SUCCESS';
export const UNLINK_MESSENGER_FAIL = 'UNLINK_MESSENGER_FAIL';
export const UNLINK_MESSENGER_RESET = 'UNLINK_MESSENGER_RESET';

// Get Messenger Status
export const GET_MESSENGER_STATUS_REQUEST = 'GET_MESSENGER_STATUS_REQUEST';
export const GET_MESSENGER_STATUS_SUCCESS = 'GET_MESSENGER_STATUS_SUCCESS';
export const GET_MESSENGER_STATUS_FAIL = 'GET_MESSENGER_STATUS_FAIL';
export const GET_MESSENGER_STATUS_RESET = 'GET_MESSENGER_STATUS_RESET';

// Clear Errors
export const CLEAR_MESSENGER_ERRORS = 'CLEAR_MESSENGER_ERRORS';