// Notification List Actions
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_FAIL = "GET_NOTIFICATIONS_FAIL";

// Notification Details Actions
export const GET_NOTIFICATION_DETAILS = "GET_NOTIFICATION_DETAILS";
export const GET_NOTIFICATION_DETAILS_SUCCESS = "GET_NOTIFICATION_DETAILS_SUCCESS";
export const GET_NOTIFICATION_DETAILS_FAIL = "GET_NOTIFICATION_DETAILS_FAIL";

// Notification Status Actions
export const MARK_NOTIFICATION_READ = "MARK_NOTIFICATION_READ";
export const MARK_NOTIFICATION_READ_SUCCESS = "MARK_NOTIFICATION_READ_SUCCESS";
export const MARK_NOTIFICATION_READ_FAIL = "MARK_NOTIFICATION_READ_FAIL";

// Broadcast Notification Actions
export const CREATE_BROADCAST_NOTIFICATION = "CREATE_BROADCAST_NOTIFICATION";
export const CREATE_BROADCAST_NOTIFICATION_SUCCESS = "CREATE_BROADCAST_NOTIFICATION_SUCCESS";
export const CREATE_BROADCAST_NOTIFICATION_FAIL = "CREATE_BROADCAST_NOTIFICATION_FAIL";

// Real-time Notification Actions
export const NEW_NOTIFICATION_RECEIVED = "NEW_NOTIFICATION_RECEIVED";
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";
export const UPDATE_NOTIFICATION_COUNT = "UPDATE_NOTIFICATION_COUNT";

// Notification Filter Actions
export const SET_NOTIFICATION_FILTER = "SET_NOTIFICATION_FILTER";
export const CLEAR_NOTIFICATION_FILTER = "CLEAR_NOTIFICATION_FILTER";

// Notification Error Actions
export const SET_NOTIFICATION_ERROR = "SET_NOTIFICATION_ERROR";
export const CLEAR_NOTIFICATION_ERROR = "CLEAR_NOTIFICATION_ERROR";