// Existing action types
export const POLICE_STATION_LIST_REQUEST = 'POLICE_STATION_LIST_REQUEST';
export const POLICE_STATION_LIST_SUCCESS = 'POLICE_STATION_LIST_SUCCESS';
export const POLICE_STATION_LIST_FAIL = 'POLICE_STATION_LIST_FAIL';

export const POLICE_STATION_SEARCH_REQUEST = 'POLICE_STATION_SEARCH_REQUEST';
export const POLICE_STATION_SEARCH_SUCCESS = 'POLICE_STATION_SEARCH_SUCCESS';
export const POLICE_STATION_SEARCH_FAIL = 'POLICE_STATION_SEARCH_FAIL';

export const POLICE_STATION_COORDINATES_REQUEST = 'POLICE_STATION_COORDINATES_REQUEST';
export const POLICE_STATION_COORDINATES_SUCCESS = 'POLICE_STATION_COORDINATES_SUCCESS';
export const POLICE_STATION_COORDINATES_FAIL = 'POLICE_STATION_COORDINATES_FAIL';

export const POLICE_STATION_SELECT = 'POLICE_STATION_SELECT';
export const POLICE_STATION_CLEAR = 'POLICE_STATION_CLEAR';

// New action types for CRUD operations
export const POLICE_STATION_CREATE_REQUEST = 'POLICE_STATION_CREATE_REQUEST';
export const POLICE_STATION_CREATE_SUCCESS = 'POLICE_STATION_CREATE_SUCCESS';
export const POLICE_STATION_CREATE_FAIL = 'POLICE_STATION_CREATE_FAIL';

export const POLICE_STATION_DETAILS_REQUEST = 'POLICE_STATION_DETAILS_REQUEST';
export const POLICE_STATION_DETAILS_SUCCESS = 'POLICE_STATION_DETAILS_SUCCESS';
export const POLICE_STATION_DETAILS_FAIL = 'POLICE_STATION_DETAILS_FAIL';

export const POLICE_STATION_UPDATE_REQUEST = 'POLICE_STATION_UPDATE_REQUEST';
export const POLICE_STATION_UPDATE_SUCCESS = 'POLICE_STATION_UPDATE_SUCCESS';
export const POLICE_STATION_UPDATE_FAIL = 'POLICE_STATION_UPDATE_FAIL';

export const POLICE_STATION_DELETE_REQUEST = 'POLICE_STATION_DELETE_REQUEST';
export const POLICE_STATION_DELETE_SUCCESS = 'POLICE_STATION_DELETE_SUCCESS';
export const POLICE_STATION_DELETE_FAIL = 'POLICE_STATION_DELETE_FAIL';

// Utility action types
export const POLICE_STATION_CLEAR_ERRORS = 'POLICE_STATION_CLEAR_ERRORS';
export const POLICE_STATION_CLEAR_SEARCH = 'POLICE_STATION_CLEAR_SEARCH';