export const POLICE_STATION_LIST_REQUEST = 'POLICE_STATION_LIST_REQUEST';
export const POLICE_STATION_LIST_SUCCESS = 'POLICE_STATION_LIST_SUCCESS';
export const POLICE_STATION_LIST_FAIL = 'POLICE_STATION_LIST_FAIL';

export const POLICE_STATION_SEARCH_REQUEST = 'POLICE_STATION_SEARCH_REQUEST';
export const POLICE_STATION_SEARCH_SUCCESS = 'POLICE_STATION_SEARCH_SUCCESS';
export const POLICE_STATION_SEARCH_FAIL = 'POLICE_STATION_SEARCH_FAIL';

export const POLICE_STATION_COORDINATES_REQUEST = 'POLICE_STATION_COORDINATES_REQUEST';
export const POLICE_STATION_COORDINATES_SUCCESS = 'POLICE_STATION_COORDINATES_SUCCESS';
export const POLICE_STATION_COORDINATES_FAIL = 'POLICE_STATION_COORDINATES_FAIL';

export const POLICE_STATION_SELECT = 'POLICE_STATION_SELECT';
export const POLICE_STATION_CLEAR = 'POLICE_STATION_CLEAR';