// Report CRUD
export const CREATE_REPORT_REQUEST = 'CREATE_REPORT_REQUEST';
export const CREATE_REPORT_SUCCESS = 'CREATE_REPORT_SUCCESS';
export const CREATE_REPORT_FAIL = 'CREATE_REPORT_FAIL';

export const GET_REPORTS_REQUEST = 'GET_REPORTS_REQUEST';
export const GET_REPORTS_SUCCESS = 'GET_REPORTS_SUCCESS';
export const GET_REPORTS_FAIL = 'GET_REPORTS_FAIL';

export const UPDATE_REPORT_REQUEST = 'UPDATE_REPORT_REQUEST';
export const UPDATE_REPORT_SUCCESS = 'UPDATE_REPORT_SUCCESS';
export const UPDATE_REPORT_FAIL = 'UPDATE_REPORT_FAIL';

export const DELETE_REPORT_REQUEST = 'DELETE_REPORT_REQUEST';
export const DELETE_REPORT_SUCCESS = 'DELETE_REPORT_SUCCESS';
export const DELETE_REPORT_FAIL = 'DELETE_REPORT_FAIL';

// Report Assignment
export const ASSIGN_STATION_REQUEST = 'ASSIGN_STATION_REQUEST';
export const ASSIGN_STATION_SUCCESS = 'ASSIGN_STATION_SUCCESS';
export const ASSIGN_STATION_FAIL = 'ASSIGN_STATION_FAIL';

export const ASSIGN_OFFICER_REQUEST = 'ASSIGN_OFFICER_REQUEST';
export const ASSIGN_OFFICER_SUCCESS = 'ASSIGN_OFFICER_SUCCESS';
export const ASSIGN_OFFICER_FAIL = 'ASSIGN_OFFICER_FAIL';

// Report Status
export const UPDATE_STATUS_REQUEST = 'UPDATE_STATUS_REQUEST';
export const UPDATE_STATUS_SUCCESS = 'UPDATE_STATUS_SUCCESS';
export const UPDATE_STATUS_FAIL = 'UPDATE_STATUS_FAIL';

// Report Feed
export const GET_REPORT_FEED_REQUEST = 'GET_REPORT_FEED_REQUEST';
export const GET_REPORT_FEED_SUCCESS = 'GET_REPORT_FEED_SUCCESS';
export const GET_REPORT_FEED_FAIL = 'GET_REPORT_FEED_FAIL';

// Report Filters
export const SET_REPORT_FILTERS = 'SET_REPORT_FILTERS';
export const CLEAR_REPORT_FILTERS = 'CLEAR_REPORT_FILTERS';

// Report Selection
export const SELECT_REPORT = 'SELECT_REPORT';
export const CLEAR_SELECTED_REPORT = 'CLEAR_SELECTED_REPORT';

// Report Cities
export const GET_CITIES_REQUEST = 'GET_CITIES_REQUEST';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';
export const GET_CITIES_FAIL = 'GET_CITIES_FAIL';

// User Reports
export const GET_USER_REPORTS_REQUEST = 'GET_USER_REPORTS_REQUEST';
export const GET_USER_REPORTS_SUCCESS = 'GET_USER_REPORTS_SUCCESS';
export const GET_USER_REPORTS_FAIL = 'GET_USER_REPORTS_FAIL';

// Reset States
export const RESET_REPORT_STATE = 'RESET_REPORT_STATE';
export const CLEAR_REPORT_ERROR = 'CLEAR_REPORT_ERROR';
