export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const GET_USER_LIST_REQUEST = 'GET_USER_LIST_REQUEST';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAILURE = 'GET_USER_LIST_FAILURE';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const UPDATE_DUTY_REQUEST = 'UPDATE_DUTY_REQUEST';
export const UPDATE_DUTY_SUCCESS = 'UPDATE_DUTY_SUCCESS';
export const UPDATE_DUTY_FAILURE = 'UPDATE_DUTY_FAILURE';

export const GET_POLICE_STATION_OFFICERS_REQUEST = 'GET_POLICE_STATION_OFFICERS_REQUEST';
export const GET_POLICE_STATION_OFFICERS_SUCCESS = 'GET_POLICE_STATION_OFFICERS_SUCCESS';
export const GET_POLICE_STATION_OFFICERS_FAILURE = 'GET_POLICE_STATION_OFFICERS_FAILURE';

export const CLEAR_USER_MESSAGE = 'CLEAR_USER_MESSAGE';
export const CLEAR_USER_ERROR = 'CLEAR_USER_ERROR';